
const WEATHER_API_ENDPOINT = 'https://api.openweathermap.org/data/2.5'

const WEATHER_API_KEY = '05508bb378ad891b493b0c886cca7a57'
const WEATHER_API_DEFAULT_CITY = 'Lublin'

const WEATHER_API_DEFAULT_PARAMS = {
    'units':'metric',
    'APPID':WEATHER_API_KEY
}

export {
    WEATHER_API_DEFAULT_CITY,
    WEATHER_API_DEFAULT_PARAMS,
    WEATHER_API_ENDPOINT,
    WEATHER_API_KEY
}